name: sdl3
description: A Dart library for accessing common SDL 3 (test) APIs using, FFI.
version: 0.1.12
homepage: https://github.com/sansuido/sdl3
repository: https://github.com/sansuido/sdl3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  change_case: ^2.0.0
