name: sdl3
description: A Dart library for accessing common SDL 3 (test) APIs using, FFI.
version: 0.1.34
homepage: https://github.com/sansuido/sdl3
repository: https://github.com/sansuido/sdl3

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  ffi: ^2.1.3

dev_dependencies:
  lints: ^4.0.0
  change_case: ^2.1.0
